#!/bin/bash

pgen=accretion_main                         # athena pgen
pythondir=vis/python                        # python directory
eosdir=heos_DIR/helm_table.dat              # eos directory
athinputfile=athinput.accretion_serial_main # athinput file
dataDIR=accretion_DIR
eos=helmholtz_gamma_etot
mkdir ${dataDIR}

python3 configure.py --prob ${pgen} --eos general/${eos} --coord spherical_polar --nscalars 2 -h5double -mpi -hdf5 --hdf5_path=${HDF5_HOME}
make clean
make

mpiexec -n 128 bin/athena -i ${athinputfile} hydro/eos_file_name=${eosdir}
mv accretion.* ${dataDIR}

python3 accretion_12panel.py ${dataDIR} ${pythondir} ${eosdir}
